spring:
  application:
    name: ec
server:
  port: 8080
eureka:
  instance:
    hostname: localhost
    preferIpAddress: true
    ipAddress: 192.168.2.210
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://192.168.2.111:8761/eureka/,http://192.168.2.120:8761/eureka/,http://192.168.2.123:8761/eureka/

endpoints:
  enabled: true
  actuator:
    enabled: true
  info:
    enabled: true